### ISSUE TITLE
Incremental Builds

### ISSUE THREAD

**Issue by natemoo-re** [withastro/roadmap#698]
- Accepted Date: 2023-09-13
- Reference Issues/Discussions:
  - https://github.com/withastro/roadmap/discussions/237
- Author: @natemoo-re 
- Champion(s): @natemoo-re 
- Implementation PR: 

# Summary

Incremental Build support in Astro aims to significantly speed up repeated runs of `astro build`. Initial builds will populate some kind of cache, which will allow subsequent builds to bypass Rollup for unchanged trees of the module graph.

# Background & Motivation

The original [incremental build support](https://github.com/withastro/roadmap/discussions/237) proposal is one of our oldest and most highly upvoted issues. Unfortunately, users have not shared many concrete examples in that thread. However, from the extensive performance profiling we've done, we know that Rollup is the main bottleneck in Astro's build process. 

Now that our rendering, Markdown, and MDX performance has been optimized about as far as we can take it, now is the time to explore new options. The best option we have is to move _as much of our build process out of Rollup_ as possible, likely with some sort of build cache. That is the goal of introducing **incremental builds**.

Why now? The reason is straightforward—caching is notoriously difficult to get right. We did not want to take on the additional complexity until our API surface was stable and our internal build process was easier to reason about. Thanks to significant effort from @bluwy and @ematipico in the past few months, we're now in a good place to tackle this.

# Goals
 
- Improve `astro build` performance
- Avoid as much repeated processing during `astro build` as possible
- Implement a generic API that enables incremental builds
- Eventually, enable incremental builds by default
- Support existing `static`, `hybrid`, and `server` outputs

# Non-Goals 

- Vendor lock-in. Incremental builds will be implemented generically, supporting our existing ecosystem of deployment platforms where possible. If a host caches assets between builds, it is likely that they will support incremental builds automatically.
- Incremental Static Regeneration (also known as [ISR](https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration) or [DPR](https://www.netlify.com/blog/2021/04/14/distributed-persistent-rendering-a-new-jamstack-approach-for-faster-builds/)). The proposal for [supporting ISR](https://github.com/withastro/roadmap/discussions/228) is an entirely different topic, not covered by this accepted proposal. **These features are not mutually exclusive.** Implementing incremental build support **benefits every user of Astro** and does not prevent Astro from potentially introducing ISR in the future.
- Future: Adapter API. Some adapters perform a significant amount of processing and may also want some form of incremental build support. To reduce the scope of this proposal, we are not considering exposing a public Adapter API for this. This may be implemented in the future as an enhancement.

**Comment by natemoo-re** [comment]
Ideally, this is something that could be solved generically on the Vite / Rollup level so that every framework could benefit from this. I'm really not sure if that's on the table, though, since the ultimate goal is to bypass Vite / Rollup as much as possible. **If this was easy to solve incremental builds in a generic way, it would have been done already.**

My current sketch for an API is very straightforward from the user's perspective:

```js
// astro.config.mjs
import { defineConfig } from 'astro/config'

export default defineConfig({
  build: { incremental: true },
  experimental: { incremental: true } // until this is stable
})
```

Unfortunately that's where the simplicity ends. To implement this, we'll likely need to:

- Generate a serializable module graph that contains every possible build input. This will need to track all module relationships (hence the "graph" part).
- Given the module graph, generate a stable checksum for each file. This will allow us to determine which parts of the graph have changed.
- On every build, we'll need to generate a new module graph and compare it to the old one. Use the checksum to determine which files need to be invalidated (changes bubble all the way up to an entry point). If any subtree of the module graph has changed shape, that also invalidates relevant portions of the module graph.
- Pass any invalidated modules as inputs to Vite. Thankfully Astro already controls every Vite input!
- As Vite generates new outputs for invalid parts of the graph, we can restore valid parts of the graph from our cache (likely in `node_modules/.cache/astro` or `node_modules/.astro`).
  - Ideal scenario: the entire module graph is valid, so the entire output is restored.
  - Worst case scenario: the entire module graph is invalid, so the entire output needs to be generated from scratch. This is currently what we do on every build.
- Any invalidated modules should be removed from the existing cache.
- Now that out output has been merged into a repaired state, execute it to prerender our `.html` files. (We can't skip directly to restoring the `.html` files because the `.js` output can depend on external data that we don't know about.)
- Populate the cache with our output for next time.
- Remove the chunks needed for prerendering from our `dist` folder

**Comment by EyePulp** [comment]
@natemoo-re Thanks for the clarity detail and documentation of your approach.  I'm eager for the performance improvements. 

More selfishly, I'm hopeful this opens the door to selective page renders.  Our use case has a lot configuration options within a single astro project, up to and including rendering or not rendering individual pages.  We can solve it today by using the dynamic route feature, but something more explicit and declarative would be very welcome, and it _feels_ like incremental builds might offer that.

Regardless, thanks for the work!

**Comment by natemoo-re** [comment]
Graduating to a full-fledged RFC. https://github.com/withastro/roadmap/pull/763

**Comment by fparedlo** [comment]
This is amazing, hope it comes in the next release!

**Comment by heyitsdoodler** [comment]
Is there a branch where work on phase 2 is being conducted?

**Comment by ImBIOS** [comment]
Wow, Phase 2 feels like a sci-fi!

**Comment by BinetStudio** [comment]
What's the current status of this feature?

**Comment by connor-baer** [comment]
> The experimental feature was removed in Astro 5. With the introduction of Content Layer the internals of how Content Collections have changed quite a lot, so how an incremental build could work needs to be rethought.

From https://github.com/withastro/roadmap/pull/763#issuecomment-2501598344
