### ISSUE TITLE
Improved env handling

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/roadmap#837]
- Accepted Date: 2024-02-09
- Reference Issues/Discussions: #822
- Author: @florian-lefebvre
- Champion(s): @florian-lefebvre (with some help!)
- Implementation PR: N/A

# Summary

This RFC aims to improve DX (and eventually security) around env variables.

# Background & Motivation

Env variables are an important part of any web application. You need to store sensitive data (think API secrets, tokens etc) without being leaked inside your git repo. But that's only the 1st part of the story. It's easy to leak this data by importing in the wrong place, eg. the frontend like [Resend a few weeks ago](https://resend.com/blog/incident-report-for-january-10-2024).

Other JS frameworks (eg. [SvelteKit](https://kit.svelte.dev/docs/modules#$env-dynamic-private)) are handling env pretty well. From my understanding, the env story is currently a bit tricky in Astro. According to the [docs](https://docs.astro.build/en/guides/environment-variables/), here is how env variables are currently handled:

- Astro uses Vite’s built-in support for environment variables
- Static variables (ie. replaced statically at build time) are accessible via `import.meta.env`
- `import.meta.env` includes some [default variables](https://docs.astro.build/en/guides/environment-variables/#default-environment-variables) like `SSR`, `BASE_URL`...
- A public variable key has to be prefixed by `PUBLIC_`
- A non public variable accessed using `import.meta.env` on the client side will be `undefined` (value will be accessible server side)
- Env variables can be loaded through `.env` (or `.env.production`, `.env.development`) and CLI
- Any non built-in variable can be [manually typed]([.env.production](https://docs.astro.build/en/guides/environment-variables/#intellisense-for-typescript))
- Runtime variables should be access using `process.env`, or following the used runtime (eg. `Deno.env.get()` for the deno adapter)
- I'm not sure if `process.env` has any protection against client-side usage (like `import.meta.env`), but I guess it doesn't

# Goals

- Provide a fully type-safe experience for environment variables, without [manual type definitions](https://docs.astro.build/en/guides/environment-variables/#intellisense-for-typescript)
- Allow users to mark environment variables as required, providing hints when a variable is missing
- Reduce user confusion between inlined, static variables and dynamic, runtime variables
- Allow adapters to specify how runtime env variables should be handled

# Non-Goals 

- Complex validation or type casting of env variables. We might want to enable this at some point, but there is likely a performance cost for this at runtime. We should punt on this if possible!
- Allowing integrations to define environment variable constraints. This is a great idea, but until we know what this feature looks like, we should consider it out of scope.
- Future: allow adapters to customize build-time variable handling. Better runtime handling is the most important problem this proposal aims to solve, but if we find an API that enables this as well, that's great.

**Comment by natemoo-re** [comment]
Great work @florian-lefebvre! I’m very excited to finally be tackling this problem.

**Comment by florian-lefebvre** [comment]
We discussed a little bit already about about those features could look. Here are some ideas:
1. **Static variables** can be made available though a virtual module and defined in the Astro config. Type safety is not an issue using codegen (depends on https://github.com/withastro/astro/pull/9952).
```ts
export default defineConfig({
	experimental: {
		env: {
			variables: ["FOO", "BAR"]
		}
	}
})
```
```ts
import { FOO, BAR } from "astro:env"
// or import * as env from "astro:env"
```
2. **Static variables validation** can be easily achieved from the `variables` list. We could allow users to choose how strict they want the check to be:
```ts
export default defineConfig({
	experimental: {
		env: {
			variables: ["FOO", "BAR"],
			checkLevel: "warn" // "error"
		}
	}
})
```
3. **Public static variables** would still be using the `PUBLIC_` prefix
4. **Dynamic variables** would be accessible through a virtual module as well. I know @lilnasy suggested using something like `Astro.env.KEY` but I think the issue is that it makes it hard to use env variables outside of `.astro` files and endpoints
5. **Dynamic variables "security"** could be improved. Currently, using `process.env` does not prevent from using a secret dynamic variable on the client-side. Since we'll have an abstraction for this, maybe we could use a proxy and depending on the key being accessed (ie. starting with the `PUBLIC_` prefix), we could check if it's being access on the client-side (`!import.meta.env.SSR`) and return undefined
6. I'm not used to the adapter API so I don't have much ideas about how it should look

**Comment by bholmesdev** [comment]
I appreciate these changes! Looking at the config, it seems odd to me that I can't have an "optional" check for variables. I agree Zod is overkill here, but primitive options per-variable, instead of a global "warn vs. error" property, would be nice.

**Comment by florian-lefebvre** [comment]
what do you think about something like this?
```ts
env: {
	variables: ({ string }) => ({
		FOO: string(),
		BAR: string({ optional: true })
	})
}
```
This way, we can set optional variables + it prepares the ground for more advanced schema

**Comment by NuroDev** [comment]
Or if it was to be even simpler something along these lines could work?
```ts
export default defineConfig({
	experimental: {
		env: {
			variables: {
				FOO: true, // Or possibly `null` instead? Some other kind of truthy value
				BAR: { optional: true, }
			},
			checkLevel: "warn" // "error"
		}
	}
});
```

**Comment by florian-lefebvre** [comment]
could be! the advantage of having `string({ optional: true })` is that in the future we could have stuff like this
```ts
env: {
	variables: ({ string, number, boolean, enum }) => ({
		FOO: string({ minLength: 5 }),
		BAR: string({ optional: true }),
		TRUE: boolean(),
		ENV: enum(["dev", "prod"])
	})
}
```

**Comment by NuroDev** [comment]
IMO if the plan is to offer that level of validation control then it may make more sense to just expose Zod like is already done in content collection configs?

**Comment by florian-lefebvre** [comment]
I think it's better to avoid zod here for 2 reasons
1. It's hard to serialize and deserialize (we'll need to pass stuff to a virtual import, I already tried and it requires at least 2 3rd party libs + some hacks; or a distinct entrypoint but it feels like it's a bit too much). It's better if we own format so that we can generate a schema ourselves
2. zod contains a lot of stuff not relevant to env (eg. functions, objects, void etc) and not everything will work as expected. For example:
	- `z.number` won't work, you need to use `z.coerce.number`
	- `z.boolean` is even trickier (see https://env.t3.gg/docs/recipes#booleans). By having our own format we can abstract those for the users and improve the DX

**Comment by florian-lefebvre** [comment]
Maybe related to this RFC https://github.com/withastro/docs/discussions/5328

**Comment by alexanderniebuhr** [comment]
I've been giving it some thought, and I'm leaning towards not reinventing the wheel when it comes to validation logic. Considering the existing solutions available, and the familiarity that Astro users have with `zod`, I'd warmly recommend that we either skip validation altogether or opt to integrate `zod` into our implementation.

**Comment by florian-lefebvre** [comment]
I'm not suggesting to not use zod at all, just not in the public interface. I've been working on it tonight for `astro-env` and as soon as I have something to show (probably this week), I'll post here

**Comment by florian-lefebvre** [comment]
Well I got distracted by other contributions since then 😅 but here is the PR! Useful links are on the PR description to see how the API looks: https://github.com/florian-lefebvre/astro-env/pull/4

**Comment by matthewp** [comment]
@florian-lefebvre have you thought about runtime environment variables much? this is something that's come up recently with `@astrojs/db` which needs to read runtime variables but can't easily do so while working in various non-Node environments.

Here's the start of an idea (maybe we can improve)

```js
// Default export
import getEnv from "astro:env"

getEnv('FOO'); // always retrieved at runtime
```

__adapter.js__
```js
'astro:config:done': ({ setAdapter }) => {
  setAdapter({
    name: '@matthewp/my-adapter',
    serverEntrypoint: '@matthewp/my-adapter/server.js',
    envEntrypoint: '@matthewp/my-adapter/env.js'
  });
},
```

__env.js__
```js
export default function(key) {{
  return Deno.getEnv(key);
}
```

cc @alexanderniebuhr not sure if this works for Cloudflare or not.

**Comment by florian-lefebvre** [comment]
@matthewp I suggested this and this is kinda what I have in mind! But apparently it has to be tied to the request because of cloudflare (so it would most likely be available as `Astro.env.FOO`)

**Comment by alexanderniebuhr** [comment]
I mean it could work, if the `env.js` could have access to `Astro.locals`

**Comment by florian-lefebvre** [comment]
I'm not familiar enough with the adapters api to know what's possible tbh!

**Comment by matthewp** [comment]
Ok, I figured this was probably a constraint. The only issue with the `Astro.env` idea is that's only accessible by Astro components. I think we'll want to figure out a solution that works for any module, Astro, JS or otherwise.

**Comment by lilnasy** [comment]
The solution could be `AsyncContext` or `AsyncLocalStorage` - users would call `getEnv()` wherever and it will retrieve from the environment associated with currently "active" request. It would still have to error at the top-level on cloudflare because there is active request and no global environment.

`AsyncLocalStorage` is a WinterCG standard, but requires enabling node compat on cloudflare, which isn't straightforward from what I understand, and that may be a blocker. `AsyncContext` is a stage 2 tc39 proposal.

**Comment by alexanderniebuhr** [comment]
> It would still have to error at the top-level on cloudflare because there is active request and no global environment.

Correct I think that is important to understand that there is a _"global"_ context, but it is not recommended to use it for env, and we need to think about env per request.. However this is not a Cloudflare only issue, other runtimes with a isolate approach have the same logic.

> `AsyncLocalStorage` is a WinterCG standard, but requires enabling node compat on cloudflare, which isn't straightforward from what I understand, and that may be a blocker.

There is some nuances to this, so `AsyncLocalStorage` wouldn't work out-of-the-box with Cloudflare Pages, however it does work with the **`nodejs_compat`** flag _(which is different to the `node_compat` flag)_. 
Additionally the import would have to look like `import { AsyncLocalStorage } from 'node:async_hooks';`
ref: https://developers.cloudflare.com/workers/runtime-apis/nodejs/asynclocalstorage/


Enabling **`nodejs_compat`** in theory doesn't have any downsides for the user _(`node_compat` has downsides)_, users need to configure it manually to make sure their Astro project works though. I don't know if that is something we want, looking at UX?
There are plans to use `wrangler.toml` configuration file for Cloudflare Pages, once Cloudflare ships that, we could add a base `wrangler.toml` with the correct flag settings when using `astro add cloudflare` and document it when users choose to install manually.

In addition to that, we would have to decide if we want to add a check and tell users they forgot the flag or not?
ref: https://github.com/cloudflare/next-on-pages/blob/9900517223d34612d503b0489d3383c3b4453cd2/packages/next-on-pages/templates/_worker.js/index.ts#L34-L37

**Comment by ematipico** [comment]
@alexanderniebuhr out of curiosity, how do you set and read environment variables with Cloudflare?

**Comment by alexanderniebuhr** [comment]
So I'll try to answer this as detailed as possible, but still as consise as possible.

The whole message only talks about "runtime" environment variables, build/compile time environment variables, are a completly different story.

You do set environment variables using the Cloudflare Dashboard, for Workers you can also use `wrangler.toml` and `.dev.vars` files, Pages will get config file support in the future, but it doesn't have it yet.

Pages/Workers _(I'll try to make sure to highlight any differences if needed)_ do have a concept of environment variables on a per-Page/Worker and per-request basis. These are not accessible automatically via the process.env API. It is possible to manually copy these values into process.env if you need to, and those will be globally persistent for all Workers running in the same isolate and context. Be aware, however, that means env variables could leak inside the same isolate and context. In addition any value on `process.env` will coerce that value into a `string`.

Cloudflare recommends strongly that you/framworks do not replace the entire `process.env` object with the request env object. It will cause unexpected bahviour for other Workers running in the same isolate.

Cloudflare has some [docs](https://developers.cloudflare.com/workers/runtime-apis/nodejs/process/#processenv) around this.

---

In general you can access the environment variables in the request handler. This looks a little different for Workers and Pages, but the concept is general the same. Pages (Astro) uses the [**Module Worker Syntax.**](https://developers.cloudflare.com/workers/runtime-apis/handlers/fetch/)

```js
export default {
  async fetch(request, env, ctx) {
    // env is the object that contains your environment variables and bindings.
  },
};
```

We (Astro) currently overwrite the whole `process.env` completly ([reference](https://developers.cloudflare.com/workers/runtime-apis/handlers/fetch/)), which I elaborated on above, is not the correct way. The next major version of the Adapter v10, will remove this. (However that means right now users should be able to access the environment variables via `process.env` as long as they only need a string value. This wouldn't work for any Cloudflare Bindings)

The other options for Users to access the request based environment variables is via `Astro.locals.runtime.env` ([reference](https://github.com/withastro/adapters/blob/main/packages/cloudflare/src/entrypoints/server.advanced.ts#L49-L60)). However this has the downside that it doesn't work in `.js` or `.ts` files.

**Comment by matthewp** [comment]
@florian-lefebvre is it a goal that you can use this package within your Astro config? Many users ask for the ability to use `import.meta.env` in their Astro config but they cannot. Not saying this proposal needs to solve this problem, just asking.

**Comment by florian-lefebvre** [comment]
No this is out of scope, actually I didn't even know people wanted that!

**Comment by ematipico** [comment]
> No this is out of scope, actually I didn't even know people wanted that!

Yeah it's something that a lot of people started to do since JS config files started to be a thing: ability to tweak it based on environment variables.

I would personally discourage this kind of pattern

**Comment by florian-lefebvre** [comment]
Alright so time to recap!

### Recap and API proposal based on feedback

#### Astro config
```ts
import { defineConfig, envField } from "astro/config"

export default defineConfig({
	experimental: {
		env: {
			staticSchema: {
				FOO: envField.string(),
				BAR: envField.string({
					optional: false
				})
			},
			dynamicSchema: {
				// Same
			}
		}
	}
})
```

- User can configure schemas for static and dynamic schemas in a distinct way
- User can use strings and make them optional (through `envField.string`)
- In the future, more fields will be exposed and/or more options (eg. `envField.boolean`). Just keeping things simple for now
- This allows integrations to add env constraints as well using `updateConfig`. I know it was not planned to be tackled initially but I think it's an elegant way to tackle it with no effort
- `envField` does not use zod because we want to only support a subset BUT we'll use zod under the hood

#### Adapter API

I'm still not familiar with this API but it will probably expose a dedicated endpoint to resolve dynamic env. We'll have to figure out how to make it work with cloudflare since `env` is tied to the request.

#### Usage of static env

```ts
import { FOO, BAR } from "astro:env/static"
```

It uses `import.meta.env` under the hood so client access should be safe for sensitive data

#### Usage of dynamic env

```astro
---
Astro.env.FOO
Astro.env.BAR
---
```

This allows any adapter to work. However, it would still be nice to support a virtual import for usage outside of astro files. This requires AsyncLocalStorage so for example, it will require explicit opt-in for cloudflare through the compat flag:

```ts
import { getEnv } from "astro:env/dynamic"
```

### Your feedback is needed

I need your help on this precise topics:
1. How do we want to call the 2 types of env variables? I went for static/dynamic but I'm open to anything
2. How do we feel about having 2 distinct schemas for static/dynamic vars?
3. What do you think about `envField`? Just to clarify, `envField.string(options)` returns `{ type: "string", ...options }` under the hood
4. What do you think about having 2 APIs for dynamic variables? I don't see any other possibilities to remain cloudflare-friendly

### The plan

I plan to implement stuff little by little as it will be easier to work on and to review:
1. Static env (`staticSchema` in the astro config, `astro:env/static` and validation in a vite plugin)
2. `envField`
3. Dynamic env (`dynamicSchema` in the astro config, adapter API and `Astro.env`)
4. Dynamic env virtual module `astro:env/dynamic` using ALS

**Comment by matthewp** [comment]
## On types

Since environment variables are always strings what happens if you do `envField.number()`? With Zod that would throw. What we really want in this case is to cast it, right? Assuming so, what happens if we make it cast, but it's NaN? In other words, is there special handling for all of these built-in types?

## static vs dynamic

I don't really see the reason for the static vs. dynamic split in the config (or in the modules). What do we gain from that?

**Comment by florian-lefebvre** [comment]
> Since environment variables are always strings what happens if you do envField.number()? With Zod that would throw. What we really want in this case is to cast it, right? Assuming so, what happens if we make it cast, but it's NaN? In other words, is there special handling for all of these built-in types?

Under the hood, that would be `z.coerce.number()`. I think a case where such an abstraction shines is for booleans:
```ts
// under the hood
z
      .string()
      // only allow "true" or "false"
      .refine((s) => s === "true" || s === "false")
      // transform to boolean
      .transform((s) => s === "true"),
```

> I don't really see the reason for the static vs. dynamic split in the config (or in the modules). What do we gain from that?

Maybe the benefit is to make sure people won't use the dynamic way for static variables? I'm fine with using one `schema` tho

**Comment by alexanderniebuhr** [comment]
> Since environment variables are always strings

@matthewp That's not 100% true for Cloudflare 👀

**Comment by florian-lefebvre** [comment]
I forgot about this **little** detail... So adapters should be able to override how zod works under the hood and possibly extend them? But that's not true for static variables right?

**Comment by alexanderniebuhr** [comment]
That is only relevant for runtime variables which you set via Cloudflare Dashboard or `wrangler.toml`.

**Comment by matthewp** [comment]
I'm not sure about supporting functions and objects, etc. The goal of the RFC says:

> Provide a fully type-safe experience for environment variables, without [manual type definitions](https://docs.astro.build/en/guides/environment-variables/#intellisense-for-typescript)

Environment variables can't be functions or objects. They are always strings that can be cast to so something else. So casting a JSON string to an object seems fine. But functions doesn't make sense to me.

Also, these things won't exist in dev mode, so I would expect them to throw unless marked as optional.

**Comment by matthewp** [comment]
I would like to see the type that's returned by `envField.string()`. If there's a desire to extend this type then it needs to be well-defined.

**Comment by florian-lefebvre** [comment]
This is just syntaxic sugar for a descriminated union:
```ts
{
	type: "string",
	optional: false
	// ...
}
```
I just like this API *à la* [Keystatic](https://keystatic.com/docs/fields/number#usage-example)

**Comment by bluwy** [comment]
Awesome work! I quite like the direction for the validation.

I don't mind the separation between static and dynamic fields. That makes it clear what environment variables can be dynamically set in the deployment platform. If we combine it, maybe we could also support something like `envField.static()` and `envField.dynamic()`?

I also think that we should limit the env values to primitives like strings and numbers for now.

Also, do we want to tackle prevention of leaking sensitive environment variables? Unlike SvelteKit with its separate dimension of public/private, I think in Astro we can assume static = public and dynamic = private. And we make sure that dynamic env vars are not used in the client side.

Lastly, I'm a bit concerned with how dynamic env var will be implemented. Would we have to do the validation in runtime instead? And does that brings in a lot of dependency?

**Comment by florian-lefebvre** [comment]
About separating static/dynamic, here is what I shared at the end of the cloudflare env thread:

> Actually, reading this convo reminded me why I think we need 1 schema per env variables type (static/dynamic). In the case of a cloudflare binding, that's a runtime thing but people would be able to try to access it through astro:env/static, and that would fail. Maybe there's a more elegant way than having 2 schemas, like adding a property on each field

I think Bjorn's idea is pretty elegant: we could have something like this:
```ts
// or envField.dynamic
envField.static({
	type: "string",
	optional: false
})
// OR the opposite
envField.string({
	context: "static", // "dynamic"
	optional: false
})
```
I don't mind having `getEnv` for static usage as well. We just need to see if there's a single `getEnv` for both static and dynamic values.

Regarding validation of dynamic env, I think it will be done at runtime (when calling `getEnv`, maybe we have a way to add caching within the same request) using `zod` since it's already included in astro. It should not require any other library afaik

**Comment by florian-lefebvre** [comment]
If zod is problematic, I think it's fine to do some validation ourselves. I mean, given that we are going to only support a tiny subset of zod's api, it will be easy (and lightweight) to implement

**Comment by bholmesdev** [comment]
Of the APIs I've seen presented, I'd prefer an extension function like `envField.static(...)` and `envField.dynamic(...)`. These match the type conventions for Astro DB columns.

That said, I'm not very comfortable with the "static" vs. "dynamic" naming. I haven't seen this convention in other frameworks, and it isn't immediately clear as a user what these names mean. I also noticed Bjorn mention this above:

> Unlike SvelteKit with its separate dimension of public/private, I think in Astro we can assume static = public and dynamic = private. And we make sure that dynamic env vars are not used in the client side.

If this is the case, would it make sense to use a more standard convention like `envField.variable(...)` and `envField.secret(...)`, or `envField.public(...)` and `envField.private(...)`? Having used platforms like Vercel, GitHub, and Cloudflare, I understand the difference between variables and secrets as a user. The encoding mechanism (static vs. dynamic) becomes an implementation detail users don't have to think about.

**Comment by florian-lefebvre** [comment]
I don't think saying "static = public and dynamic = private" is true. If I understand correctly, we currently have:

| | Build time | Runtime |
| --- | --- | --- |
| Public | `import.meta.env.PUBLIC_FOO` | `process.env.*` |
| Private | `import.meta.env.FOO` | N/A |

I think public/private could still be kept defined by the `PUBLIC_` prefix, but having a way to distinct build time / runtime variables is really important imo. I think that's the nice part about sveltekit, they have clear imports for each of these 4 cases (see [docs]($env-dynamic-private)).

**Comment by bluwy** [comment]
(I think you have runtime-public and runtime-private flipped)

I don't think supporting runtime-public makes a lot of sense. For buildtime-private, yeah I was thinking that maybe we don't support it and force users to runtime-private instead. _If it was sensitive, maybe it shouldn't be inlined in the first place_. And that users will always have to set the private env var on their deployment platform.

If we still want to support it, I also don't mind, just that I would prefer a chain API like:

```js
env.static().optional() // implicitly private by default?
env.static().public().default("")
env.dynamic().private().optional()
env.dynamic().public().optional()
```

If the API is like `envField.static({ type: "string", optional: false })`, we could directly accept an object instead? `{ type: "string", scope: "static", optional: false }`

**Comment by florian-lefebvre** [comment]
I quite like this API tbh! I don't especially mind supporting or not public dynamic variables either

I see a few issues with chaining tho. What happens if we have this case?
```ts
schema: {
	FOO: env.static().public()
}
```
Since it doesn't have the `PUBLIC_` prefix, should we error and explain it's required? What about this case if we don't support public dynamic vars?
```ts
schema: {
	PUBLIC_FOO: env.dynamic()
}
```
Should we error saying it can't be public?

**Comment by bluwy** [comment]
Yeah I think we should error in those two cases and treat it as a config validation error. We currently have zod validate the Astro config, and we could do a nested validation within it too.

**Comment by matthewp** [comment]
What is the definition of static and dynamic? What do these terms mean?

**Comment by florian-lefebvre** [comment]
Static means available at build time through `import.meta.env`. Dynamic means available at runtime and depends on the adapter, eg `process.env` or `Deno.env.get()`

**Comment by alexanderniebuhr** [comment]
I also struggled with those terms at the beginning, maybe we should refer to them as `build/compile-time` vs `runtime` variables?

**Comment by florian-lefebvre** [comment]
Yeah it's a but longer but way clearer

**Comment by ematipico** [comment]
Good suggestion @alexanderniebuhr, I prefer this naming convention!

**Comment by florian-lefebvre** [comment]
So to recap since last time I asked for feedback

> How do we want to call the 2 types of env variables? I went for static/dynamic but I'm open to anything

Let's go for `buildTime` / `runtime`

> How do we feel about having 2 distinct schemas for static/dynamic vars?
> What do you think about envField? Just to clarify, envField.string(options) returns { type: "string", ...options } under the hood

Instead of having 2 schemas, it will be part of `envField` as suggested by Bjorn

> What do you think about having 2 APIs for dynamic variables? I don't see any other possibilities to remain cloudflare-friendly

We are going to use ALS + virtual import only.

---

More questions now!

1. Ema expressed concerns about overriding constants exported from `astro:env/static`. I still think it improves the DX (it's also done by sveltekit) but I'd like your opinions. If we don't do this, what should we do? I think we need 2 distinct imports anyway at least?
2. Do we want to support public runtime variables? Or are we fine with only keeping them private (ie. always undefined on the client even with the `PUBLIC_` prefix)?

**Comment by bluwy** [comment]
1. `buildTime` and `runtime` reads weird to me 😄  Personally I prefer static/dynamic but not a hill I'd die on.
2. I think overriding constants is fine as it's only an implementation detail.
3. How would we support public runtime variables though? For example, how would `PUBLIC_FOO` be referenced in runtime? If the variable is already public, they can switch to buildtime instead.

**Comment by ematipico** [comment]
About the naming, I think we should reach out to docs for an opinion.

We keep naming things based on what are internally, but we have to consider how docs teach concepts to our users. For example they try to push the term "on demand" instead of dynamic/SSR.

To echo what @bluwy said, naming is hard and subjective, so I would feel more comfortable to use any name that docs suggests, because at the end **they will teach the narrative to our users**.

**Comment by florian-lefebvre** [comment]
A few comments from @FredKSchott on Discord

**Fred**
> SST calls these "Secrets" (runtime) vs. "Parameters" (static) which I always liked, although it implies that runtime things are always secret which may not always be neccessarily true.
>
> However, if the big thing you need to know about static is that they get bundled into your build itself, then a name should definitely make that distinction clear
>
> aka the distinction I would care about is that it's not really about runtime vs. buildtime, but more about "included in your build = insecure" vs. "read from the server at runtime = secure" (which gets back to why I think "Secrets vs. Parameter" is actually pretty good, all things considered) 
>
> no strong objections to the other names though, at the end of the day. Static vs. Dynamic is pretty good as well.

**Florian**
> the thing is, "included in your build" is not necessarily unsecure. I mean, if you prefix it with PUBLIC_ then it means it's safe to use client side right?

**Fred**
> Anything in the deployed code (not read from ENV) should be considered insecure as a default, yes. For ex:
> - Deploying it to your own machine = the secret is readable  to any user account with SSH + file read access
> - Deploying it to Vercel = the secret is readable from the "source" tab (possibly Netlify, CF, etc. as well?)

**Comment by bholmesdev** [comment]
That's some good perspective! I notice Cloudflare and GitHub also use "secret" vs "variable" (or parameter in SST's case). It seems like we're not agreed on whether buildtime vs. runtime is _synonymous_ with variable vs. secret. I think static vs. dynamic would be more agreeable thinking it over

**Comment by alexanderniebuhr** [comment]
The only issue I have with `static vs. dynamic` is, that those variables are not really "static" or "dynamic". Both types can be changed/overriden by the user in the runtime. Both types can be updated with a config update _(for some hosts that needs a redeployment for both types)_.
I associate a changing value as "dynamic", e.g. timestamp

**Comment by klizter** [comment]
Built in support for dynamic `PUBLIC` environment variables would be great. We just recently ran into the issue of getting the same build to work in several different environments, but since public variables are baked in at build time it would not work. I hope this will work in the future, for now we have to handle this issue outside Astro.

**Comment by bluwy** [comment]
@klizter If we support dynamic public env vars, how would you envision the API to pass in the different env var value dynamically? (specifically client-side / browsers). On the server-side, it's simpler with `process.env` or `Deno.env`, but on the client-side, it's not clear to me how that's being passed. Hence, I suggested above to not support it.

**Comment by florian-lefebvre** [comment]
Stage 3 RFC available in #894

**Comment by nemanjam** [comment]
How do I access env variables in the `astro.config.ts` itself? Can they be defined and used in the same file? For example i store site url as env variable `site: SITE_URL`.

```ts
import { envSchema } from './src/utils/env';
const { SITE_URL } = CONFIG;

export default defineConfig({
  site: SITE_URL, // I still must use process.env.SITE_URL here?
  experimental: {
    env: {
      schema: envSchema,
    }
  },
...
});
```

**Comment by florian-lefebvre** [comment]
Hey @nemanjam thanks for bringing this up! It's out of scope of **this** RFC but we're not against it! That's something often asked and source of confusion so I think that's something we could tackle. Would you mind creating a new roadmap discussion for this with as much info/context as you can? Then we can share it to gather more feedback and usecases

**Comment by nemanjam** [comment]
> [@nemanjam](https://github.com/nemanjam) Any news on this? Maybe binding the `defineConfig` implementation to a specific [mode](https://docs.astro.build/en/guides/environment-variables/#in-the-astro-config-file) would be an interesting approach? E.g. by changing the signature of `defineConfig()` to `defineConfig( mode )` which then uses the according [env.{mode}](https://docs.astro.build/en/guides/environment-variables/#in-the-astro-config-file) file for e.g. `astro build --mode {mode}` ?

Just use relative import in `astro.config.ts`, see this:

```ts
// astro.config.ts

import { envSchema, PROCESS_ENV } from './src/config/process-env';
```

https://github.com/nemanjam/nemanjam.github.io/blob/bde0a3e04e1a152615a768c25324821cf4f83cdb/astro.config.ts#L14

**Comment by sandstrom** [comment]
> You can't have runtime env variables in static site. Take static pages, sitemap.xml and rss.xml for example, how would you set vars in there at runtime?

Good points, I've clarified my question.
